In [1]:
import os
import sys

In [2]:
sys.path.append(os.path.join(os.getcwd(), "../"))

In [3]:
import pandas as pd
import numpy as np

In [4]:
from datetime import datetime

In [5]:
from src.python.utils import load_file_chunks

In [6]:
DATA_PATH = os.path.join(os.getcwd(), "../", "data")
OPTIONS_DATA_PATH = os.path.join(DATA_PATH, "spx_options.csv")
UNDERLYING_DATA_PATH = os.path.join(DATA_PATH, "spx_underlying.csv")

In [13]:
start_date = datetime(2014, 2, 12)
end_date = datetime(2014, 2, 12)

In [14]:
options_df = load_file_chunks(OPTIONS_DATA_PATH, start_date, end_date)

In [16]:
options_df['strike_price'] = options_df['strike_price'] / 1000

In [17]:
options_df

,secid,date,exdate,cp_flag,strike_price,best_bid,best_offer,volume,open_interest,impl_volatility,...,gamma,vega,theta,optionid,am_settlement,ss_flag,index_flag,issuer,exercise_style,am_set_flag
1431250,108105,2014-02-12,2014-02-22,C,1000.0,815.6,818.1,0,16496,NaN,...,NaN,NaN,NaN,101934899,1,0,1,CBOE S&P 500 INDEX,E,NaN
1431251,108105,2014-02-12,2014-02-22,C,1025.0,790.6,793.1,0,0,NaN,...,NaN,NaN,NaN,101934900,1,0,1,CBOE S&P 500 INDEX,E,NaN
1431252,108105,2014-02-12,2014-02-22,C,1050.0,765.6,768.1,0,0,NaN,...,NaN,NaN,NaN,101934901,1,0,1,CBOE S&P 500 INDEX,E,NaN
1431253,108105,2014-02-12,2014-02-22,C,1075.0,740.6,743.1,0,0,NaN,...,NaN,NaN,NaN,101934902,1,0,1,CBOE S&P 500 INDEX,E,NaN
1431254,108105,2014-02-12,2014-02-22,C,1100.0,715.6,718.1,0,1,NaN,...,NaN,NaN,NaN,101934903,1,0,1,CBOE S&P 500 INDEX,E,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1433994,108105,2014-02-12,2014-04-04,P,1930.0,116.5,121.6,0,0,0.126673,...,0.002051,120.17330,-81.79069,102702626,0,0,1,CBOE S&P 500 INDEX,E,NaN
1433995,108105,2014-02-12,2014-04-04,P,1940.0,124.0,131.5,0,0,0.122158,...,0.001708,96.48944,-70.27138,102702627,0,0,1,CBOE S&P 500 INDEX,E,NaN
1433996,108105,2014-02-12,2014-04-04,P,1950.0,133.6,140.6,0,0,0.121833,...,0.001438,81.02841,-63.86909,102702628,0,0,1,CBOE S&P 500 INDEX,E,NaN
1433997,108105,2014-02-12,2014-04-04,P,1975.0,157.9,165.5,0,0,0.132875,...,0.001080,66.38250,-60.47162,102702629,0,0,1,CBOE S&P 500 INDEX,E,NaN
1433998,108105,2014-02-12,2014-04-04,P,2000.0,183.0,190.2,0,0,0.146943,...,0.000876,59.55776,-60.35909,102702630,0,0,1,CBOE S&P 500 INDEX,E,NaN

In [20]:
start_date_underlying = datetime(2014, 4, 4)

In [21]:
underlying_df = load_file_chunks(UNDERLYING_DATA_PATH, start_date_underlying, start_date_underlying)

In [22]:
underlying_df.tail()

       secid       date    close    return
1070  108105 2014-04-04  1865.09 -0.012537